stages:
  - build
  - test
  - deploy

image: debian:stable

build:debian:
  stage: build
  script:
  - apt-get update
  - apt-get install -y python3-all python3-docopt python3-setuptools
                       python3-docopt python3-pkg-resources python3-xdg
                       python3-chardet
  - python3 setup.py install
  - isbg --version

build:pypi:
  stage: build
  script:
  - apt-get update && apt-get install -y python3-pip
  - pip3 install -r requirements-build.txt
  - pip3 install -r requirements.txt
  - python3 setup.py install
  - isbg --version

test:doc:
  stage: test
  script:
  - apt-get update
  - apt-get install -y python3-sphinx python3-sphinx-rtd-theme python3-docopt
                       python3-recommonmark
  - sphinx-build -b html docs testdocs
  artifacts:
    paths:
    - testdocs
  except:
  - master

test:pytest:
  stage: test
  script:
  - apt-get update && apt-get install -y python3-pytest python3-pytest-runner
                                         python3-recommonmark python3-docopt
  - pytest-3 tests

pages:
  stage: deploy
  script:
  - apt-get update
  - apt-get install -y python3-sphinx python3-sphinx-rtd-theme python3-docopt
                       python3-recommonmark
  - sphinx-build -b html docs public
  artifacts:
    paths:
      - public
  only:
  - master
