stages:
  - test
  - build
  - deploy

image: debian:stable

test:docs:
  stage: test
  script:
  - apt-get update
  - apt-get install -y python3-sphinx python3-sphinx-rtd-theme python3-docopt
                       python3-recommonmark
  - make html
  - mv build/sphinx/html testdocs
  artifacts:
    paths:
    - testdocs
    expire_in: 1 week
  except:
  - master

test:unit:
  stage: test
  script:
  - apt-get update && apt-get install -y make python3-pytest python3-pytest-runner
                                         python3-recommonmark python3-docopt
  - make test

test:pypi:
  stage: test
  script:
  - apt-get update && apt-get install -y twine
  - python3 setup.py sdist
  - twine check dist/*

install:debian:
  stage: build
  script:
  - apt-get update
  - apt-get install -y python3-all python3-docopt python3-setuptools
                       python3-docopt python3-pkg-resources python3-xdg
                       python3-chardet
  - python3 setup.py install
  - isbg --version

install:pypi:
  stage: build
  script:
  - apt-get update && apt-get install -y python3-pip
  - pip3 install -r requirements-build.txt
  - pip3 install -r requirements.txt
  - python3 setup.py install
  - isbg --version

pages:
  stage: deploy
  script:
  - apt-get update
  - apt-get install -y python3-sphinx python3-sphinx-rtd-theme python3-docopt
                       python3-recommonmark
  - make html
  - mv build/sphinx/html public
  artifacts:
    paths:
      - public
  only:
  - master
